version: "3.8"
services:
  helpay_app:
    container_name: helpay_app
    build:
      context: .
    depends_on:
      - helpay_db
    environment:
      SERVICE_NAME: helpay_app
      DB_CONNECTION: mysql
      DB_DRIVER: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: 3306
    networks:
      - app_network

  helpay_nginx:
    container_name: helpay_nginx
    build:
      context: ./docker/.
    volumes:
      - "./public:/usr/src/app/public"
    environment:
      NGINX_FPM_HOST: helpay_app
      NGINX_ROOT: /var/www/public
    ports:
      - "8000:80"
    depends_on:
      - helpay_app
    networks:
      - app_network

  helpay_db:
    container_name: helpay_db
    image: mysql:5
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: ${DB_HOST}
    ports:
      - "8899:3306"
    volumes:
      - "./storage/db-data:/var/lib/mysql"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
